
project_id = "vsrkmtebffntocpjapxz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
image_transformation = true
request_timeout = "10s"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[functions.mpesa-payment]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
