// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgpjnbdrmwrupeqhjqpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncGpuYmRybXdydXBlcWhqcXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTkyMzQsImV4cCI6MjA2NjU5NTIzNH0.oxzq8UCKxVhL86YOkJcvjx2xBKGXWcC8LWOU6Hvh1Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);